### PR TITLE
Use Prettier

### PR DESCRIPTION
**Pull request by nickserv**
This uses the same Markdown config as our other repos for consistent formatting

### CODE REVIEW

**Comment by nickserv** [comment]
I was thinking of adding actions or hooks too, but not sure it's worth the effort

**Comment by eps1lon** [comment]
Did you check every repository has its own `.prettierrc` or that they want that configuration?

**Comment by nickserv** [comment]
Config sharing only works for GitHub configs. I'm intentionally not sharing the Prettier config because I just want to format Markdown files in this repository.

If other repos want to share Prettier config, they can extend `kcd-scripts/prettier`.

**Comment by eps1lon** [comment]
Can you link the docs for these kind of repos?

**Comment by nickserv** [comment]
[Creating a default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

**Review by eps1lon — APPROVED** [review]

**Pull request merged**
